version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
        - npm test
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

# test:
#   phases:
#     preTest:
#       commands:
#     #    - kill -9 $(lsof -t -i:3000)
#         - npm install
#         - npm install wait-on
#         - npm install  mocha@5.2.0 mochawesome mochawesome-merge mochawesome-report-generator
#         - npm start
#         #& npx wait-on http://localhost:3000"
# #    test:
#  #     commands:
#   #      - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
#   # postTest:
#     #  commands:
#      #   - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
#   artifacts:
#     baseDirectory: cypress
#     configFilePath: '**/mochawesome.json'
#     files:
#       - '**/*.png'
#       - '**/*.mp4'
